#dockerfile, image, container

FROM python:3.9

COPY . example_1/

WORKDIR /example_1

RUN apt-get update && apt-get install -y libeccodes-dev
RUN pip install -r requirements.txt

CMD ls && chmod 755 start.sh && ./start.sh